add check if neighbourhood is already installed
coasys/ad4m pull request #217
Opened 2023-01-30 17:36 UTC by jdeepee

I did not need to implement holochain DNA deletion logic for languages since we now install DNA's provided by languages at the holochain app level, with each language having its own app & internal DNA's. 

Since it is not possible to install multiple languages, it should not be possible to install duplicate holochain apps. It may however be possible to have two different languages expose the same underlying holochain DNA, in this case maybe it would be best to have the two languages share one app / dna. We can address this later if it arrises as a common pattern.

2023-01-31 12:44 UTC, lucksus requested changes

2023-01-31 12:44 UTC, lucksus commented on executor/src/tests/neighbourhood.ts
> -                expect(join.neighbourhood!.meta.links.length).to.be.equal(1);
Why removing the `joinFromUrl()` here? Now we're not testing the whole Neighbourhood flow anymore. That doesn't seem right.

2023-01-31 12:44 UTC, lucksus commented on executor/src/tests/neighbourhood.ts
> -                expect(join.neighbourhood!.meta.links.length).to.be.equal(1);
Ah, I now see that the test was exercising only Alice. So it must have triggered the new condition in `installNeighbourhood`. What we need to do instead is having Bob joining the NH and keeping these assertions.

2023-01-31 16:59 UTC, jdeepee commented on executor/src/tests/neighbourhood.ts
> -                expect(join.neighbourhood!.meta.links.length).to.be.equal(1);
That test is already implement, its in the same file, called: 'can be created by Alice and joined by Bob'

2023-02-01 16:01 UTC, lucksus approved these changes

2023-02-01 22:26 UTC, merged