Login proxy server when unlock or generate agent.
coasys/ad4m pull request #303
Opened 2023-03-06 08:41 UTC by kaichaosun

Fix https://github.com/perspect3vism/ad4m/issues/285

2023-03-20 11:59 UTC, lucksus requested changes
Great! Just need a changelog entry.

2023-03-20 12:04 UTC, lucksus reviewed
Ok, I've added a changelog entry, but now I'm wondering if we should actually have it this way. It will create more load on our proxy even for users that are not using this feature. Would be better to remember between startups if the proxy was activated and only restore the previous state.

2023-03-21 08:30 UTC, kaichaosun commented
> if we should actually have it this way. It will create more load on our proxy even for users that are not using this feature.

The login process when startup ad4m will not setup the proxy connection, it only login agents did in cloudflare kv db, which be used for credential check when set up the proxy connection later.

Have every user to login is not ideal, we can add the advanced setting when initialize the ad4m, an item in this advanced setting can be `do you want to use proxy (mobile maybe better?)`

2023-03-22 14:33 UTC, lucksus approved these changes

2023-03-22 15:46 UTC, merged