SDNA Active record implementation
coasys/ad4m pull request #356
Opened 2023-04-03 20:44 UTC by fayeed

2023-04-06 10:49 UTC, lucksus requested changes

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +    this.#baseExpression = baseExpression ? baseExpression : `entry://${makeRandomPrologAtom(24)}`;
```suggestion
    this.#baseExpression = baseExpression ? baseExpression : Literal.from(makeRandomPrologAtom(24)).toUrl();
```

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +    if (!subject) {
Don't really understand what this is for.. ?
`subject` isn't used below. if the base is not an instance of the class (which createSubject() would fix) we already jumped out of this function with the throw above...

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +    }
I think these lines can go
```suggestion
```

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +            this['timestamp'] = expression.timestamp;
That doesn't seem right. The expression we're setting in a property could be created by somebody else an definitely at a different timestamp than the base..

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +  private async setProperties(key: string, value: any) {
This only sets one property, right?
```suggestion
  private async setProperty(key: string, value: any) {
```

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +      if (setter) {
Why not let Prolog do the matching and only look at the given property?
```js
await this.#perspective.infer(`subject_class("${this.#subjectClass}", C), property_setter(C, ${key}, Setter)`)
```

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +    const subject = await this.#perspective.createSubject(this, this.#baseExpression);
```suggestion
```

2023-04-06 10:49 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +  }
update() and save() are the same, right?

2023-04-06 10:49 UTC, lucksus commented on tests/js/integration.test.ts
> +            })
Needs tests for collections. Would suggest to clone the collection tests from the subject proxy above.

2023-04-06 11:39 UTC, fayeed commented on core/src/subject/SubjectEntity.ts
> +    const subject = await this.#perspective.createSubject(this, this.#baseExpression);
The find all doesn't work if I don't create a subject instance for it.

2023-04-11 20:54 UTC, lucksus requested changes
Would like `find()` to be changed to `static all()` as described below... Rest is great!

2023-04-11 20:54 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +  async find() {
Find it weird that this is an instance method, and not a static class method. I understand that we need a PerspectiveProxy to do anything, but we can provide that as argument. Clearer interface than having to create an instance which is not used as an instance of the Subject Class..
```suggestion
  static async all(perspective: PerspectiveProxy) {
```

2023-04-11 20:54 UTC, lucksus commented on core/src/subject/SubjectEntity.ts
> +    const proxies = await this.#perspective.getAllSubjectProxies(this.#subjectClass)
```suggestion
    let subjectClass = await perspective.stringOrTemplateObjectToSubjectClass(this)
    const proxies = await perspective.getAllSubjectProxies(subjectClass)
```

2023-04-11 20:54 UTC, lucksus commented on tests/js/integration.test.ts
> +
With above changes, this becomes much clearer...
```suggestion
                    const recipes = new Recipe.all(perspective!)

```

2023-04-12 13:01 UTC, lucksus approved these changes
👍

2023-04-12 14:04 UTC, merged